name: Android CI

on:
  workflow_dispatch:      # cho phép bấm "Run workflow" thủ công
  push:
    branches: [ "main" ]  # auto build khi push lên main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Grant execute permission for Gradle
      run: chmod +x ./gradlew

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
